version: '3.8'

services:
  app:
    build: .
    ports:
      - "8095:8095"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shopwave
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db
    networks:
      - shopwave-network

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shopwave
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shopwave-network

networks:
  shopwave-network:
    driver: bridge

volumes:
  postgres-data: 