spring:
  # Development Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # JPA Configuration for development
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  
  # H2 Console for development
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Development Mail Configuration (using MailHog or similar)
  mail:
    host: localhost
    port: 1025
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

# Development JWT Configuration
jwt:
  secret: dev-secret-key-for-development-only-not-for-production-use
  expiration: 3600000 # 1 hour for development
  refresh-expiration: 86400000 # 24 hours for development

# Development Payment Configuration
payment:
  iyzico:
    api-key: sandbox-api-key-for-development
    secret-key: sandbox-secret-key-for-development
    base-url: https://sandbox-api.iyzipay.com
    webhook-secret: dev-webhook-secret

# Development CORS Configuration
app:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:3001,http://localhost:4200
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

# Development Logging Configuration
logging:
  level:
    com.acanbiler.shopwave: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
    org.springframework.transaction: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Development Server Configuration
server:
  port: 8080
  error:
    include-stacktrace: always
    include-message: always
    include-binding-errors: always